var trips =
    {
        "title": 'Trips',
        "description": "",
        "data": [
            {
                "title": "Metus Vulputate",
                "date": "June 22, 2020",
                'avatar': "images/placeholder.png",
                'image': "images/group-travel.jpg",
                "duration": "6 DAYS / 5 NIGHTS",
                "price": '$1,195',
                "regular": "$1,395 <br> OR JUST $195 DOWN",
                "content": "Ridiculus rutrum. Malesuada sem ornare fringilla suscipit imperdiet dapibus vulputate consectetuer neque odio massa taciti, sit parturient congue viverra iaculis bibendum amet litora sollicitudin per odio auctor fringilla, erat eget nonummy tincidunt venenatis potenti nullam volutpat conubia pulvinar egestas nec vestibulum eros hendrerit aliquet Nunc nascetur Dictum, consequat consectetuer eu faucibus inceptos sit suspendisse. Et vulputate ridiculus sociis rhoncus taciti odio proin nam aptent, nisi integer velit ligula feugiat scelerisque. <br>Pulvinar semper proin duis. A elementum tortor Eget imperdiet ultricies odio. Pulvinar natoque, id ante ligula taciti facilisis volutpat duis. Nisi sit accumsan vivamus fusce pharetra laoreet nibh parturient augue ultrices faucibus nullam diam lorem hymenaeos rutrum. Taciti mollis proin duis. Bibendum nullam pulvinar ullamcorper, pede platea nullam inceptos pellentesque. Viverra magnis, habitant ut lacinia. Praesent quam. Rhoncus quisque convallis mi, metus donec malesuada pulvinar dignissim magna tempor sagittis neque Volutpat volutpat consequat scelerisque morbi eleifend senectus, tincidunt lobortis bibendum. Turpis lacus consequat primis etiam dui. Posuere hendrerit aptent praesent porta nostra pretium penatibus tincidunt lorem orci eleifend varius commodo sollicitudin tellus eros dignissim ligula, pretium consequat semper feugiat. Luctus molestie nam venenatis donec mi conubia augue, curae; placerat ipsum justo. <br>Auctor senectus erat turpis sociis odio nec nascetur curae; elit. Magnis dui tortor tempus lectus lectus accumsan tortor ullamcorper magnis morbi tincidunt curae; litora. Sem tristique. Parturient. At imperdiet arcu. Magnis. Habitant duis non tellus sed risus hymenaeos. Laoreet non purus a eros suspendisse commodo conubia. Ullamcorper bibendum accumsan curabitur sagittis taciti feugiat montes. Mauris dignissim at id class massa convallis porttitor est molestie maecenas. Vivamus sem eros non placerat suspendisse mus orci pretium turpis quam non, elit sociis at non, in lacinia mi ac id, vehicula nunc tortor diam lectus gravida porttitor pretium ultrices orci sodales donec lacinia. Nascetur elementum fusce eros luctus convallis. Lorem tempor hendrerit duis.",
                "url": "trip-1.html"
            },
            {
                "title": "Metus Vulputate 2",
                "date": "June 23, 2020",
                'avatar': "images/placeholder.png",
                'image': "images/group-travel.jpg",
                "duration": "6 DAYS / 5 NIGHTS",
                "price": '$1,195',
                "regular": "$1,395 <br> OR JUST $195 DOWN",
                "content": "Ridiculus rutrum. Malesuada sem ornare fringilla suscipit imperdiet dapibus vulputate consectetuer neque odio massa taciti, sit parturient congue viverra iaculis bibendum amet litora sollicitudin per odio auctor fringilla, erat eget nonummy tincidunt venenatis potenti nullam volutpat conubia pulvinar egestas nec vestibulum eros hendrerit aliquet Nunc nascetur Dictum, consequat consectetuer eu faucibus inceptos sit suspendisse. Et vulputate ridiculus sociis rhoncus taciti odio proin nam aptent, nisi integer velit ligula feugiat scelerisque. <br>Pulvinar semper proin duis. A elementum tortor Eget imperdiet ultricies odio. Pulvinar natoque, id ante ligula taciti facilisis volutpat duis. Nisi sit accumsan vivamus fusce pharetra laoreet nibh parturient augue ultrices faucibus nullam diam lorem hymenaeos rutrum. Taciti mollis proin duis. Bibendum nullam pulvinar ullamcorper, pede platea nullam inceptos pellentesque. Viverra magnis, habitant ut lacinia. Praesent quam. Rhoncus quisque convallis mi, metus donec malesuada pulvinar dignissim magna tempor sagittis neque Volutpat volutpat consequat scelerisque morbi eleifend senectus, tincidunt lobortis bibendum. Turpis lacus consequat primis etiam dui. Posuere hendrerit aptent praesent porta nostra pretium penatibus tincidunt lorem orci eleifend varius commodo sollicitudin tellus eros dignissim ligula, pretium consequat semper feugiat. Luctus molestie nam venenatis donec mi conubia augue, curae; placerat ipsum justo. <br>Auctor senectus erat turpis sociis odio nec nascetur curae; elit. Magnis dui tortor tempus lectus lectus accumsan tortor ullamcorper magnis morbi tincidunt curae; litora. Sem tristique. Parturient. At imperdiet arcu. Magnis. Habitant duis non tellus sed risus hymenaeos. Laoreet non purus a eros suspendisse commodo conubia. Ullamcorper bibendum accumsan curabitur sagittis taciti feugiat montes. Mauris dignissim at id class massa convallis porttitor est molestie maecenas. Vivamus sem eros non placerat suspendisse mus orci pretium turpis quam non, elit sociis at non, in lacinia mi ac id, vehicula nunc tortor diam lectus gravida porttitor pretium ultrices orci sodales donec lacinia. Nascetur elementum fusce eros luctus convallis. Lorem tempor hendrerit duis.",
                "url": "trip-2.html"
            },
            {
                "title": "Metus Vulputate 3",
                "date": "June 24, 2020",
                'avatar': "images/placeholder.png",
                'image': "images/group-travel.jpg",
                "duration": "6 DAYS / 5 NIGHTS",
                "price": '$1,195',
                "regular": "$1,395 <br> OR JUST $195 DOWN",
                "content": "Ridiculus rutrum. Malesuada sem ornare fringilla suscipit imperdiet dapibus vulputate consectetuer neque odio massa taciti, sit parturient congue viverra iaculis bibendum amet litora sollicitudin per odio auctor fringilla, erat eget nonummy tincidunt venenatis potenti nullam volutpat conubia pulvinar egestas nec vestibulum eros hendrerit aliquet Nunc nascetur Dictum, consequat consectetuer eu faucibus inceptos sit suspendisse. Et vulputate ridiculus sociis rhoncus taciti odio proin nam aptent, nisi integer velit ligula feugiat scelerisque. <br>Pulvinar semper proin duis. A elementum tortor Eget imperdiet ultricies odio. Pulvinar natoque, id ante ligula taciti facilisis volutpat duis. Nisi sit accumsan vivamus fusce pharetra laoreet nibh parturient augue ultrices faucibus nullam diam lorem hymenaeos rutrum. Taciti mollis proin duis. Bibendum nullam pulvinar ullamcorper, pede platea nullam inceptos pellentesque. Viverra magnis, habitant ut lacinia. Praesent quam. Rhoncus quisque convallis mi, metus donec malesuada pulvinar dignissim magna tempor sagittis neque Volutpat volutpat consequat scelerisque morbi eleifend senectus, tincidunt lobortis bibendum. Turpis lacus consequat primis etiam dui. Posuere hendrerit aptent praesent porta nostra pretium penatibus tincidunt lorem orci eleifend varius commodo sollicitudin tellus eros dignissim ligula, pretium consequat semper feugiat. Luctus molestie nam venenatis donec mi conubia augue, curae; placerat ipsum justo. <br>Auctor senectus erat turpis sociis odio nec nascetur curae; elit. Magnis dui tortor tempus lectus lectus accumsan tortor ullamcorper magnis morbi tincidunt curae; litora. Sem tristique. Parturient. At imperdiet arcu. Magnis. Habitant duis non tellus sed risus hymenaeos. Laoreet non purus a eros suspendisse commodo conubia. Ullamcorper bibendum accumsan curabitur sagittis taciti feugiat montes. Mauris dignissim at id class massa convallis porttitor est molestie maecenas. Vivamus sem eros non placerat suspendisse mus orci pretium turpis quam non, elit sociis at non, in lacinia mi ac id, vehicula nunc tortor diam lectus gravida porttitor pretium ultrices orci sodales donec lacinia. Nascetur elementum fusce eros luctus convallis. Lorem tempor hendrerit duis.",
                "url": "trip-3.html"
            },
            {
                "title": "Metus Vulputate 4",
                "date": "June 25, 2020",
                'avatar': "images/placeholder.png",
                'image': "images/group-travel.jpg",
                "duration": "6 DAYS / 5 NIGHTS",
                "price": '$1,195',
                "regular": '$1,395 <br> OR JUST $195 DOWN',
                "content": "Ridiculus rutrum. Malesuada sem ornare fringilla suscipit imperdiet dapibus vulputate consectetuer neque odio massa taciti, sit parturient congue viverra iaculis bibendum amet litora sollicitudin per odio auctor fringilla, erat eget nonummy tincidunt venenatis potenti nullam volutpat conubia pulvinar egestas nec vestibulum eros hendrerit aliquet Nunc nascetur Dictum, consequat consectetuer eu faucibus inceptos sit suspendisse. Et vulputate ridiculus sociis rhoncus taciti odio proin nam aptent, nisi integer velit ligula feugiat scelerisque. <br>Pulvinar semper proin duis. A elementum tortor Eget imperdiet ultricies odio. Pulvinar natoque, id ante ligula taciti facilisis volutpat duis. Nisi sit accumsan vivamus fusce pharetra laoreet nibh parturient augue ultrices faucibus nullam diam lorem hymenaeos rutrum. Taciti mollis proin duis. Bibendum nullam pulvinar ullamcorper, pede platea nullam inceptos pellentesque. Viverra magnis, habitant ut lacinia. Praesent quam. Rhoncus quisque convallis mi, metus donec malesuada pulvinar dignissim magna tempor sagittis neque Volutpat volutpat consequat scelerisque morbi eleifend senectus, tincidunt lobortis bibendum. Turpis lacus consequat primis etiam dui. Posuere hendrerit aptent praesent porta nostra pretium penatibus tincidunt lorem orci eleifend varius commodo sollicitudin tellus eros dignissim ligula, pretium consequat semper feugiat. Luctus molestie nam venenatis donec mi conubia augue, curae; placerat ipsum justo. <br>Auctor senectus erat turpis sociis odio nec nascetur curae; elit. Magnis dui tortor tempus lectus lectus accumsan tortor ullamcorper magnis morbi tincidunt curae; litora. Sem tristique. Parturient. At imperdiet arcu. Magnis. Habitant duis non tellus sed risus hymenaeos. Laoreet non purus a eros suspendisse commodo conubia. Ullamcorper bibendum accumsan curabitur sagittis taciti feugiat montes. Mauris dignissim at id class massa convallis porttitor est molestie maecenas. Vivamus sem eros non placerat suspendisse mus orci pretium turpis quam non, elit sociis at non, in lacinia mi ac id, vehicula nunc tortor diam lectus gravida porttitor pretium ultrices orci sodales donec lacinia. Nascetur elementum fusce eros luctus convallis. Lorem tempor hendrerit duis.",
                "url": "trip-4.html"
            },
            {
                "title": "Metus Vulputate 5",
                "date": "June 26, 2020",
                'avatar': "images/placeholder.png",
                'image': "images/group-travel.jpg",
                "duration": "6 DAYS / 5 NIGHTS",
                "price": '$1,195',
                "regular": "$1,395 <br> OR JUST $195 DOWN",
                "content": "Ridiculus rutrum. Malesuada sem ornare fringilla suscipit imperdiet dapibus vulputate consectetuer neque odio massa taciti, sit parturient congue viverra iaculis bibendum amet litora sollicitudin per odio auctor fringilla, erat eget nonummy tincidunt venenatis potenti nullam volutpat conubia pulvinar egestas nec vestibulum eros hendrerit aliquet Nunc nascetur Dictum, consequat consectetuer eu faucibus inceptos sit suspendisse. Et vulputate ridiculus sociis rhoncus taciti odio proin nam aptent, nisi integer velit ligula feugiat scelerisque. <br>Pulvinar semper proin duis. A elementum tortor Eget imperdiet ultricies odio. Pulvinar natoque, id ante ligula taciti facilisis volutpat duis. Nisi sit accumsan vivamus fusce pharetra laoreet nibh parturient augue ultrices faucibus nullam diam lorem hymenaeos rutrum. Taciti mollis proin duis. Bibendum nullam pulvinar ullamcorper, pede platea nullam inceptos pellentesque. Viverra magnis, habitant ut lacinia. Praesent quam. Rhoncus quisque convallis mi, metus donec malesuada pulvinar dignissim magna tempor sagittis neque Volutpat volutpat consequat scelerisque morbi eleifend senectus, tincidunt lobortis bibendum. Turpis lacus consequat primis etiam dui. Posuere hendrerit aptent praesent porta nostra pretium penatibus tincidunt lorem orci eleifend varius commodo sollicitudin tellus eros dignissim ligula, pretium consequat semper feugiat. Luctus molestie nam venenatis donec mi conubia augue, curae; placerat ipsum justo. <br>Auctor senectus erat turpis sociis odio nec nascetur curae; elit. Magnis dui tortor tempus lectus lectus accumsan tortor ullamcorper magnis morbi tincidunt curae; litora. Sem tristique. Parturient. At imperdiet arcu. Magnis. Habitant duis non tellus sed risus hymenaeos. Laoreet non purus a eros suspendisse commodo conubia. Ullamcorper bibendum accumsan curabitur sagittis taciti feugiat montes. Mauris dignissim at id class massa convallis porttitor est molestie maecenas. Vivamus sem eros non placerat suspendisse mus orci pretium turpis quam non, elit sociis at non, in lacinia mi ac id, vehicula nunc tortor diam lectus gravida porttitor pretium ultrices orci sodales donec lacinia. Nascetur elementum fusce eros luctus convallis. Lorem tempor hendrerit duis.",
                "url": "trip-5.html"
            },
        ]
    }